---
- name: Exploring line in file
  # run against planetexpress group but not farnsworth
  hosts: planetexpress
  gather_facts: true   # required for when statement
  connection: ansible.builtin.ssh   # default

  vars:

    fileloc: "/var/log/bootstrap.log"

  tasks:
    
    - name: "Insert a line into {{ fileloc }}"
      ansible.builtin.lineinfile:
        path: "{{ fileloc }}"
        regexp: "^Setting up lib.*"
        line: "REDACTED BY ANSIBLE lineinfile module"
        backup: true
      become: true
      when: ansible_os_family == "Debian"   # restricts to only Debian hosts, depends on gather_facts
