---
- name: Intro to T and F conditionals
  hosts: localhost
  gather_facts: false

  vars:

    bool_var: true
    msg_var: "TIME TO PANIC!"

  tasks:

    - name: Runs when bool_var is true
      ansible.builtin.debug:
        msg: "{{ msg_var }}"
      when: bool_var|bool

    - name: Runs when bool_var is false
      ansible.builtin.debug:
        msg: "DONT PANIC!"
      when: not bool_var|bool 
