---
- name: Apache server installed
  hosts: web
  gather_facts: false
  
  tasks:

    # The package module tries to select yum or apt or pkg5 automatically
    - name: latest Apache version installed
      ansible.builtin.package:
        name: apache2
        state: latest
      become: true

    - name: Apache enabled and running
      ansible.builtin.service:
        name: apache2
        enabled: true
        state: started
      become: true

    # Copy index.html into the service
    - name: copy index.html
      ansible.builtin.copy:
        src: ~/mycode/files/index.html
        dest: /var/www/html
      become: true

    # If dst is directory download every time but only replace if dst is different
    - name: Download a copy of apache2.conf
      ansible.builtin.get_url:
        url: https://raw.githubusercontent.com/rzfeeser/alta3files/master/apache2.conf
        dest: /etc/apache2/
      become: true
      notify:
        - restart_apache

  # This will ONLY run if tasks call them
  handlers:
    - name: restart_apache
      service:
        name: apache2
        state: restarted
      become: true
