---
- name: A simple file playbook
  hosts: planetexpress
  gather_facts: true
  connection: ansible.builtin.ssh

  tasks:
  - name: make a directory
    ansible.builtin.file:
      path: ~/output/
      state: directory

  - name: use copy to list the user home directory location in ~/output/path.txt
    ansible.builtin.copy:
      content: "{{ ansible_env.HOME }}"
      dest: ~/output/path.txt
      force: yes
