---
- name: Playbook with the register keyword
  hosts: planetexpress
  connection: ansible.builtin.ssh

  tasks:

    - name: Issue a trivial command
      ansible.builtin.command: ls /lib/
      register: contentz_lib

    - name: debug - display data returned
      ansible.builtin.debug:
        var: contentz_lib
        # msg: "{{ contentz_lib }}"   # Use Var, it is simplier

    - name: debug - standard error
      ansible.builtin.debug:
        var: contentz_lib.stderr

    - name: debug - standard out
      ansible.builtin.debug:
        var: contentz_lib.stdout
