---
- name: Learning about blocks
  hosts: planetexpress
  connection: ansible.builtin.ssh
  gather_facts: false

  tasks:

    - name: BLOCK - This is what we want to TRY to do
      block:

        - name: Example Task
          ansible.builtin.shell: echo 'My single task ran' > example.txt

        - name: Example Task
          ansible.builtin.shell: echo 'My second task ran' >> example.txt

        - name: Example Task
          ansible.builtin.shell: echo 'My third task ran' >> example.txt
