---
- name: A playbook showing the file module
  hosts: planetexpress
  gather_facts: true 
  connection: ssh

  tasks:
    - name: Create directory where space station documents will reside
      ansible.builtin.file:
        path: "~/station_docs/"
        state: directory
        mode: "0755"

    - name: Copy content into a file with the year-mo-day
      ansible.builtin.copy:
        # the var "fileuser" is a host variable
        # ansible_date_time.date is defined by gather_facts
        dest: "~/station_docs/navdata-{{ ansible_date_time.date }}.txt"
        content: "Earth\nMars\nSaturn\nEuropa\n"

