---
- name: Network Commands by Vendor
  hosts: allvendors
  gather_facts: false

  vars_files:

    - ~/switch.creds

  tasks:

    - name: Run an agnostic command
      ansible.netcommon.cli_command:
        command: "{{ commandtoshowinterfaces }}"
      register: results

    - name: show results
      ansible.builtin.debug:
        var: results
