---
- name: How to prompt for variables
  hosts: professors   # Connect to the professors group
  gather_facts: false

  vars_prompt:

    - name: ansible_ssh_pass   # Password to connect to the hosts in the professors group
      prompt: What is your ssh password?   # Question to ask
      private: true   # Do not reveal what is typed, Optional

  tasks:

    - name: Connect to the professors and install figlet
      ansible.builtin.yum:
        name: figlet
        state: present
      become: true
