---
- name: removing example user and sandbox group
  hosts: raiders
  connection: ssh
  gather_facts: false

  tasks:
  # Remove the user 'exampleuser'
  - name: remove a user
    ansible.builtin.user:
      name: exampleuser
      state: absent
      remove: yes
    become: yes

  # Remove the group 'sandbox'
  - name: Remove the group sandbox
    ansible.builtin.group:
      name: sandbox
      state: absent
    become: yes
